#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# snatched from https://github.com/paulirish/dotfiles/blob/master/symlink-setup.sh
print_question() {
    # Print output in yellow
    printf "\e[0;33m  [?] $1\e[0m"
}
