#!/bin/sh
ROUTE_TABLE="lex_integrity"
GATEWAYIP=$5

# Make sure that there is a rule to lookup lex_integrity route table when marked packets arrive
ip rule add from all fwmark 0x1 lookup $ROUTE_TABLE

# Create the correct routes in table "lex_integrity" according to this instantiation of the tunnel
ip route replace default via $GATEWAYIP table $ROUTE_TABLE
ip route append default via 127.0.0.1 dev lo table $ROUTE_TABLE
ip route flush cache
