# Home Manager common config for all my machines
{
  config,
  pkgs,
  lib,
  ...
}:
let
  palette = import ./rose-pine.nix;
in
{
  imports = [
    ./fzf.nix
    ./zsh.nix
    ./tmux.nix
    ./git.nix
    ./ssh.nix
    ./ghostty.nix
  ];

  nix.registry = {
    nixpkgs-master = {
      from = {
        id = "nixpkgs-master";
        type = "indirect";
      };
      to = {
        type = "github";
        owner = "NixOS";
        repo = "nixpkgs";
        ref = "master";
      };
    };
    # Stable channel for running pre-built packages without local compilation
    # e.g. `nix run nixpkgs-stable#foo`
    nixpkgs-stable = {
      from = {
        id = "nixpkgs-stable";
        type = "indirect";
      };
      to = {
        type = "github";
        owner = "NixOS";
        repo = "nixpkgs";
        ref = "nixos-25.11";
      };
    };
  };
  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;

  programs.git.settings.user.email = lib.mkDefault "mail@axellarsson.nu";

  home.packages = with pkgs; [
    # common packages I always want
    nix
    nil
    nixfmt
    ripgrep
    jq
    fd
    nh
    shellcheck
    shfmt
    pandoc

    neovim
    tree-sitter

    pkgs.pythonEnv

    git
    pspg
    zsh-completions
  ];

  home.file.".kube/kubie.yaml".source = ./kubie.yaml;
  home.file.".config/pgcli/config".source = ./pgcli.conf;
  home.file.".pspgconf".source = ./pspg.conf;
  home.file.".psqlrc".source = ./psqlrc.conf;
  home.file.".config/nvim" = {
    source = lib.cleanSourceWith {
      src = ./nvim;
      filter = path: type: !(lib.hasSuffix "lazy-lock.json" path);
    };
    recursive = true;
  };
  home.file."dev" = {
    source = ./dev;
    recursive = true;
  };

  programs = {
    bat =
      let
        # Both variants generated from the palette (see tmtheme.nix); bat's theme
        # option wants a directory, so write each into its own.
        mkTheme =
          name: variant:
          pkgs.writeTextDir "${name}.tmTheme" (
            lib.generators.toPlist { escape = true; } (import ./tmtheme.nix variant)
          );
      in
      {
        enable = true;
        themes = {
          # home-manager rebuilds the bat cache on activation, so no manual
          # `bat cache --build` needed
          rose-pine = {
            src = mkTheme "rose-pine" palette.main;
            file = "/rose-pine.tmTheme";
          };
          rose-pine-dawn = {
            src = mkTheme "rose-pine-dawn" palette.dawn;
            file = "/rose-pine-dawn.tmTheme";
          };
        };
        config = {
          # bat probes the terminal background (OSC 11) and picks one of these,
          # so it follows ghostty without any help from `theme sync`.
          theme = "auto";
          theme-dark = "rose-pine";
          theme-light = "rose-pine-dawn";
        };
      };

    eza = {
      enable = true;
      enableZshIntegration = true;
    };

    direnv = {
      enable = true;
      # hook output is baked into the zshrc at build time (see zsh.nix)
      enableZshIntegration = false;
      nix-direnv.enable = true;
    };

    zoxide = {
      enable = true;
      # init output is baked into the zshrc at build time (see zsh.nix)
      enableZshIntegration = false;
    };

    yazi =
      let
        rosePineSrc = pkgs.fetchFromGitHub {
          owner = "rose-pine";
          repo = "yazi";
          rev = "c89d745573d4fcfe0550fe6646f9f9ab1c0e51db";
          sha256 = "sha256-9e3dXViWl1rK9BPrGAFfs9ZL/tsG6Njz6ksuU6AIrFY=";
        };
      in
      {
        enable = true;
        enableZshIntegration = true;
        shellWrapperName = "y";
        theme = {
          flavor = {
            dark = "rose-pine";
            light = "rose-pine-dawn";
          };
        } // builtins.fromTOML (builtins.readFile "${rosePineSrc}/themes/rose-pine.toml");
        flavors = {
          rose-pine = "${rosePineSrc}/flavors/rose-pine.yazi";
          rose-pine-dawn = "${rosePineSrc}/flavors/rose-pine-dawn.yazi";
          rose-pine-moon = "${rosePineSrc}/flavors/rose-pine-moon.yazi";
        };
      };

    delta = {
      enable = true;
      options = {
        navigate = true;
        # light/dark and syntax-theme come from ~/.config/git/theme.gitconfig,
        # regenerated by `theme sync` and included from config/git.nix.
      };
      enableGitIntegration = true;
    };

  };
}
